export const crafts = [
  {
    name: 'Pashmina Weaving',
    origin: 'Kashmir Valley',
    tag: 'Textiles',
    icon: '⧖',
    color: '#c9a84c',
    bg1: '#2a1f0a', bg2: '#0e0c08', accent: 'rgba(201,168,76,',
    pattern: 'pashmina', photo: '/crafts/pashmina.jpg',
    desc: 'Spun from the finest Changthangi goat wool at 14,000 ft, each Pashmina shawl demands months of meticulous handwork — from raw fibre to finished weave — by artisans who inherit the craft at birth.',
  },
  {
    name: 'Papier Mâché',
    origin: 'Srinagar, Old City',
    tag: 'Decorative Arts',
    icon: '◈',
    color: '#e07840',
    bg1: '#2a1008', bg2: '#100a05', accent: 'rgba(224,120,64,',
    pattern: 'papier', photo: '/crafts/papier.jpg',
    desc: 'Vibrant lacquered boxes, vases, and ornaments painted with intricate chinar-leaf and floral motifs. The Naqash families of Srinagar have perfected this 600-year-old technique through unbroken lineages.',
  },
  {
    name: 'Kani Weave',
    origin: 'Kanihama Village',
    tag: 'Textile Heritage',
    icon: '✦',
    color: '#50a878',
    bg1: '#081a10', bg2: '#050e08', accent: 'rgba(80,168,120,',
    pattern: 'kani', photo: '/crafts/kani.jpg',
    desc: 'An ancient twill-tapestry technique producing hypnotic buta patterns using tiny wooden spools (kanis) instead of a shuttle. A single shawl can require 2–3 years and up to 5,000 spools in play simultaneously.',
  },
  {
    name: 'Walnut Wood Carving',
    origin: 'Shopian District',
    tag: 'Woodcraft',
    icon: '❋',
    color: '#c48050',
    bg1: '#1e1008', bg2: '#0e0804', accent: 'rgba(196,128,80,',
    pattern: 'walnut', photo: '/crafts/walnut.jpg',
    desc: 'Relief carving on Kashmiri walnut — the finest furniture hardwood in Asia — featuring chinar leaves, paisley, and layered arabesques. Each piece is unique; no two grains nor carvings are alike.',
  },
  {
    name: 'Crewel Embroidery',
    origin: 'Kashmir Valley',
    tag: 'Needlework',
    icon: '⁕',
    color: '#a07ab8',
    bg1: '#130a1e', bg2: '#0a0610', accent: 'rgba(160,122,184,',
    pattern: 'crewel', photo: '/crafts/crewel.jpg',
    desc: 'Dense chain-stitch embroidery on coarse cotton using richly coloured woolen thread. Crewel work wraps furniture, curtains, and wall panels in bold botanical worlds — flora too vivid for any valley but Kashmir.',
  },
  {
    name: 'Copper & Silverwork',
    origin: 'Old City, Srinagar',
    tag: 'Metalcraft',
    icon: '◉',
    color: '#b8a860',
    bg1: '#1a1808', bg2: '#0e0e04', accent: 'rgba(184,168,96,',
    pattern: 'copper', photo: '/crafts/copper.jpg',
    desc: 'Hand-hammered samovars, trays, hookah bases, and jewellery — embossed with floral and geometric waqf patterns. The copper-smiths of the Bohri Kadal quarter have worked these bazaar lanes since the Mughal era.',
  },
]

export const artisans = [
  {
    name: 'Ghulam Mohammad Khanday',
    craft: 'Kani Shawl Weaver',
    location: 'Kanihama, Kashmir',
    exp: '42 yrs',
    quote: 'Each knot is a word; the finished shawl is a poem only patience can write.',
    skills: ['Kani Weave', 'Jamavar', 'Sozni Borders'],
    initial: 'G', hue: '#c9a84c',
  },
  {
    name: 'Fatima Bano Sheikh',
    craft: 'Sozni & Crewel Embroiderer',
    location: 'Srinagar Old City',
    exp: '28 yrs',
    quote: 'My needle follows the same chinar leaf my grandmother traced sixty years ago.',
    skills: ['Sozni', 'Crewel', 'Kashmiri Aari'],
    initial: 'F', hue: '#8a7a9a',
  },
  {
    name: 'Abdul Rashid Dar',
    craft: 'Walnut Wood Sculptor',
    location: 'Shopian, South Kashmir',
    exp: '35 yrs',
    quote: 'The walnut does not resist the blade — it reveals what was always inside.',
    skills: ['Relief Carving', 'Furniture', 'Screens'],
    initial: 'A', hue: '#a87c5a',
  },
  {
    name: 'Bashir Ahmad Wani',
    craft: 'Papier Mâché Naqash',
    location: 'Zaina Kadal, Srinagar',
    exp: '31 yrs',
    quote: 'A box is nothing — until the brush breathes a garden into it.',
    skills: ['Naqash Painting', 'Lacquerwork', 'Gold Inlay'],
    initial: 'B', hue: '#c47a3a',
  },
]

export const stories = [
  {
    cat: 'Heritage', accent: '#c9a84c', date: 'June 2026', read: '8 min',
    title: 'The Dying Art of Kani Weaving and Its Last Custodians',
    excerpt: 'In a small hamlet outside Srinagar, three families maintain the only unbroken tradition of pure Kani loom weaving left in all of Kashmir.',
  },
  {
    cat: 'Craft Journey', accent: '#8a7a9a', date: 'May 2026', read: '12 min',
    title: 'From Raw Pashmina to Finished Shawl: A Six‑Month Odyssey',
    excerpt: 'We followed a single Pashmina shawl from the Changpa herders of Ladakh to the Srinagar bazaar — a 4,000 km journey across altitude and artistry.',
  },
  {
    cat: 'Artisan Story', accent: '#4a8a6a', date: 'April 2026', read: '6 min',
    title: "The Women Who Stitch Kashmir's Stories in Thread and Silence",
    excerpt: 'Sozni embroiderers rarely reach the spotlight. This is the story of four women who have quietly kept their craft alive across three generations.',
  },
  {
    cat: 'Conservation', accent: '#c47a3a', date: 'March 2026', read: '10 min',
    title: 'Saving the Naqash: Racing to Document a Vanishing Craft',
    excerpt: "Kashmir's Papier Mâché masters are ageing, with few apprentices. A new documentation project is racing to archive every pattern before it is lost.",
  },
]
